defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Top Menu
        icon: restaurant
        value: 
          _section-type: top-menu
          content-block-link:
          food-image:
          day_html: 
          heading: 
          description:
          price: 
          button-text:
          button-link:
      - label: Bottom Menu
        icon: restaurant_menu
        value: 
          _section-type: bottom-menu
          content-block-link:
          food-image:
          day_html: 
          heading: 
          description:
          price: 
          button-text:
          button-link:
      - label: Hero
        icon: star
        value: 
          _section-type: hero
          content-block-link:
          hero-image:
          heading: 
          description:
          button-text: 
          button-link:
      - label: Text Area
        icon: article
        value: 
          _section-type: text-area
          content-block-link:
          heading: 
          title-1: 
          text-area-1: 
          title-2: 
          text-area-2: 
          title-3: 
          text-area-3: 
          title-4: 
          text-area-4:
          button-text: 
          button-link:
      - label: Divider 
        icon: image
        value:
          _section-type: divider
          strip: